# Generated by Django 5.1.3 on 2024-12-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='material',
            field=models.CharField(choices=[('Cotton', 'Cotton'), ('Polyester', 'Polyester'), ('Leather', 'Leather'), ('Wool', 'Wool'), ('Synthetic fabrics', 'Synthetic fabrics'), ('Other', 'Other')], default='Cotton', max_length=20),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='brand',
            field=models.CharField(choices=[('Adidas', 'Adidas'), ('Nike', 'Nike'), ('Reebok', 'Reebok'), ('Puma', 'Puma'), ('New Balance', 'New Balance'), ('Asics', 'Asics'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='category',
            field=models.CharField(choices=[('Sportswear', 'Sportswear'), ('Casualwear', 'Casualwear'), ('Childrenwear', 'Childrenwear'), ('Accessories', 'Accessories'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Purple', 'Purple'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Brown', 'Brown'), ('Gray', 'Gray'), ('Other', 'Other')], max_length=20),
        ),
    ]
