# Generated by Django 5.1.3 on 2024-12-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_clothes_gender_images_clothes_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='image',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
