# Generated by Django 5.1.3 on 2024-11-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_slider_alter_shoes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoes',
            options={'verbose_name_plural': 'Shoes'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': 'Sliders'},
        ),
        migrations.RemoveField(
            model_name='slider',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='url',
        ),
        migrations.AddField(
            model_name='shoes',
            name='image',
            field=models.ImageField(default='static/assets/default.jpg', upload_to='shoes_images/'),
        ),
    ]
